#!/bin/sh
set -euf

if [ -z ${1+x} ]; then
  cmd='default'
else
  cmd="$1"
fi

binDir=$HOME/.local/bin
configDir=$HOME/.config/notes


while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "--help"
      echo "Try 'notes [OPTION]'"
      echo
      echo "Arguments to pair with the notes command"
      echo -e "  -d --directory=[PATH_TO_NOTES_DIRECTORY]\t Location of the notes that need to be version controlled"
      echo -e "  -c --commit=[COMMIT MESSAGE]\t Default Commit Message to use when committing changes"
      exit 0
      ;;
    -c)
      shift
      if test $# -gt 0; then
        export PROCESS=$1
        echo $1
      else
        echo "no commit message specified"
        exit 1
      fi 
      shift
      ;;
    --commit*)
      export PROCESS=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
    -d)
      shift
      if test $# -gt 0; then
        export OUTPUT=$1
        echo $1
      else
        echo "no directory specified"
        exit 1
      fi
      shift
      ;;
    --directory*)
      export OUTPUT=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
    *)
      break
        echo "Welcome to Notes A simple command line tool to version control your notes"
        echo "Use 'notes --help' for more information"
      ;;
  esac
done
